#!/usr/bin/env python3
"""
SSH Knock -- Port-knock then connect over SSH.

Placeholders replaced at install time:
    __HOSTNAME__   -- target host
    __KNOCK1__     -- first knock port
    __KNOCK2__     -- second knock port
    __KNOCK3__     -- third knock port
    __SSH_PORT__   -- SSH listen port
"""

from __future__ import print_function

import os
import re
import sys
import socket
import platform
import subprocess
import threading
import time

# -- tkinter import guard ---------------------------------------------------
try:
    import tkinter as tk
except ImportError:
    print(
        "ERROR: tkinter is not installed.\n"
        "  Debian/Ubuntu:  sudo apt install python3-tk\n"
        "  Fedora/RHEL:    sudo dnf install python3-tkinter\n"
        "  macOS:          brew install python-tk\n"
        "  Windows:        reinstall Python with 'tcl/tk' option checked"
    )
    sys.exit(1)

# -- DPI awareness on Windows -----------------------------------------------
if platform.system() == "Windows":
    try:
        import ctypes
        ctypes.windll.shcore.SetProcessDpiAwareness(1)
    except Exception:
        pass

# ---------------------------------------------------------------------------
# Placeholders (server install replaces these with real values)
# ---------------------------------------------------------------------------
HOSTNAME   = "__HOSTNAME__"
KNOCK_SEQ  = [__KNOCK1__, __KNOCK2__, __KNOCK3__]
SSH_PORT   = __SSH_PORT__
KNOCK_DELAY = 0.3          # seconds between knocks

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
_SAFE_INPUT_RE = re.compile(r'^[a-zA-Z0-9._-]+$')


def _validate_input(value, label):
    """Return an error string if *value* is not safe for shell use, else None."""
    if not value:
        return "Error: %s is empty" % label
    if not _SAFE_INPUT_RE.match(value):
        return "Error: %s contains invalid characters (allowed: a-z A-Z 0-9 . _ -)" % label
    return None


def _check_placeholders():
    """Return an error string if install-time placeholders were never replaced."""
    if HOSTNAME == "__HOSTNAME__":
        return (
            "Placeholders have not been replaced.\n"
            "This client must be generated by the server install script."
        )
    return None

# ---------------------------------------------------------------------------
# Colours -- matches the 2FA gate dark theme
# ---------------------------------------------------------------------------
BG_DARK    = "#0f172a"
BG_CARD    = "#1e293b"
ACCENT     = "#0ea5e9"
ACCENT_HVR = "#38bdf8"
TEXT_PRI   = "#f1f5f9"
TEXT_SEC   = "#94a3b8"
TEXT_DIM   = "#64748b"
SUCCESS    = "#22c55e"
ERROR      = "#ef4444"
WARN       = "#f59e0b"

# ---------------------------------------------------------------------------
# Cross-platform font tuples
# ---------------------------------------------------------------------------
FONT_UI      = ("Segoe UI", "Helvetica Neue", "Ubuntu", "sans-serif")
FONT_MONO    = ("Consolas", "Menlo", "DejaVu Sans Mono", "monospace")


def _font(size, weight=""):
    """Return a tk font tuple using the UI font family."""
    if weight:
        return (FONT_UI, size, weight)
    return (FONT_UI, size)


def _mono(size):
    """Return a tk font tuple using the monospace font family."""
    return (FONT_MONO, size)


# ---------------------------------------------------------------------------
# Port-knock logic
# ---------------------------------------------------------------------------
def knock(host, port, timeout=1.0):
    """Send a single TCP SYN to *host*:*port*.

    Connection-refused / timeout is expected -- the knock daemon just needs
    to see the SYN.
    """
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(timeout)
    try:
        s.connect((host, port))
    except (socket.timeout, ConnectionRefusedError, OSError):
        pass  # normal -- knock ports are not listening
    finally:
        s.close()


def _probe_port(host, port, timeout=2.0):
    """Return True if a TCP connection to *host*:*port* succeeds."""
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(timeout)
    try:
        s.connect((host, port))
        s.close()
        return True
    except (socket.timeout, ConnectionRefusedError, OSError):
        return False


def _escape_applescript(s):
    """Escape a string for safe interpolation inside AppleScript double quotes."""
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    return s


def launch_ssh(host, user, port):
    """Open an interactive SSH session in whatever terminal is available."""
    # Build command as a list -- no shell interpolation
    ssh_args = ["ssh", "-p", str(port), "%s@%s" % (user, host)]
    ssh_cmd_str = " ".join(ssh_args)

    system = platform.system()

    if system == "Linux":
        terminals = [
            "alacritty",
            "kitty",
            "foot",
            "x-terminal-emulator",
            "gnome-terminal",
            "konsole",
            "xfce4-terminal",
            "xterm",
        ]
        for term in terminals:
            try:
                if term == "gnome-terminal":
                    cmd = [term, "--", "bash", "-lc", ssh_cmd_str + "; exec bash"]
                elif term in ("alacritty", "kitty", "foot"):
                    cmd = [term, "-e"] + ssh_args
                else:
                    cmd = [term, "-e", ssh_cmd_str]
                subprocess.Popen(cmd)
                return None
            except FileNotFoundError:
                continue
        return "No terminal emulator found (tried %s)." % ", ".join(terminals)

    elif system == "Darwin":
        safe_cmd = _escape_applescript(ssh_cmd_str)
        # Try iTerm2 first, then fall back to Terminal.app
        iterm_script = (
            'tell application "iTerm2"\n'
            '    activate\n'
            '    set newWin to (create window with default profile command "%s")\n'
            'end tell'
        ) % safe_cmd

        terminal_script = (
            'tell application "Terminal"\n'
            '    activate\n'
            '    do script "%s"\n'
            'end tell'
        ) % safe_cmd

        # Try iTerm2
        try:
            proc = subprocess.Popen(
                ["osascript", "-e", iterm_script],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            _, stderr = proc.communicate(timeout=5)
            if proc.returncode == 0:
                return None
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass

        # Fall back to Terminal.app
        try:
            subprocess.Popen(["osascript", "-e", terminal_script])
            return None
        except FileNotFoundError:
            return "osascript not found -- cannot open Terminal.app."

    elif system == "Windows":
        try:
            subprocess.Popen(["cmd.exe", "/c", "start", "cmd.exe", "/k"] + ssh_args)
            return None
        except FileNotFoundError:
            return "cmd.exe not found."

    else:
        return "Unsupported platform: %s" % system


# ---------------------------------------------------------------------------
# GUI
# ---------------------------------------------------------------------------
class KnockApp(object):
    def __init__(self, root):
        self.root = root
        self.root.title("SSH Knock")
        self.root.configure(bg=BG_DARK)
        self.root.resizable(False, False)

        # -- Thread safety flags (use threading.Event) ----------------------
        self._busy = threading.Event()
        self._closing = False

        # -- Centre the window roughly --------------------------------------
        w, h = 440, 420
        sx = root.winfo_screenwidth()
        sy = root.winfo_screenheight()
        x = (sx - w) // 2
        y = (sy - h) // 2
        root.geometry("%dx%d+%d+%d" % (w, h, x, y))

        # -- macOS window focus ---------------------------------------------
        root.lift()
        root.attributes("-topmost", True)
        root.after(200, lambda: root.attributes("-topmost", False))

        # -- WM_DELETE_WINDOW handler ---------------------------------------
        root.protocol("WM_DELETE_WINDOW", self._on_close)

        # -- Placeholder guard ----------------------------------------------
        placeholder_err = _check_placeholders()

        self._build_ui()

        # -- Bind Enter key to trigger knock --------------------------------
        root.bind("<Return>", lambda e: self._on_knock())

        if placeholder_err:
            self._set_status(placeholder_err, ERROR)
            self.btn.configure(state="disabled", bg="#475569")

    # ---- safe after -------------------------------------------------------
    def _safe_after(self, ms, func, *args):
        """Schedule func via root.after only if the window is not closing."""
        if not self._closing:
            self.root.after(ms, func, *args)

    # ---- close handler ----------------------------------------------------
    def _on_close(self):
        self._closing = True
        self.root.destroy()

    # ---- helpers ----------------------------------------------------------
    def _label(self, parent, text, **kw):
        defaults = dict(bg=BG_CARD, fg=TEXT_PRI, font=_font(10))
        defaults.update(kw)
        return tk.Label(parent, text=text, **defaults)

    def _entry(self, parent, textvariable, **kw):
        return tk.Entry(
            parent,
            textvariable=textvariable,
            bg="#334155",
            fg=TEXT_PRI,
            insertbackground=TEXT_PRI,
            relief="flat",
            font=_font(10),
            highlightthickness=1,
            highlightcolor=ACCENT,
            highlightbackground="#475569",
            **kw
        )

    # ---- build (pack/grid, no place()) ------------------------------------
    def _build_ui(self):
        # -- Outer padding via a frame in the root --------------------------
        outer = tk.Frame(self.root, bg=BG_DARK)
        outer.pack(fill="both", expand=True, padx=16, pady=16)

        # -- Card frame ----------------------------------------------------
        card = tk.Frame(outer, bg=BG_CARD, highlightbackground="#334155",
                        highlightthickness=1)
        card.pack(fill="both", expand=True)

        inner = tk.Frame(card, bg=BG_CARD)
        inner.pack(fill="both", expand=True, padx=18, pady=14)

        # -- Title ----------------------------------------------------------
        title = tk.Label(inner, text="SSH Knock", bg=BG_CARD, fg=TEXT_PRI,
                         font=_font(15, "bold"), anchor="w")
        title.pack(fill="x", pady=(0, 6))

        # -- Divider --------------------------------------------------------
        div = tk.Frame(inner, bg="#334155", height=1)
        div.pack(fill="x", pady=(0, 10))

        # -- Hostname -------------------------------------------------------
        self._label(inner, "Hostname", anchor="w").pack(fill="x")
        self.var_host = tk.StringVar(value=HOSTNAME)
        host_entry = self._entry(inner, self.var_host)
        host_entry.pack(fill="x", ipady=4, pady=(2, 10))

        # -- SSH User -------------------------------------------------------
        self._label(inner, "SSH User", anchor="w").pack(fill="x")
        self.var_user = tk.StringVar(value="root")
        user_entry = self._entry(inner, self.var_user)
        user_entry.pack(fill="x", ipady=4, pady=(2, 10))

        # -- Knock sequence (read-only) -------------------------------------
        self._label(inner, "Knock Sequence", fg=TEXT_SEC,
                    font=_font(9), anchor="w").pack(fill="x")
        seq_text = "  >  ".join(str(p) for p in KNOCK_SEQ) + "  >  SSH :" + str(SSH_PORT)
        self._label(inner, seq_text, fg=TEXT_DIM,
                    font=_mono(9), anchor="w").pack(fill="x", pady=(2, 12))

        # -- Button ---------------------------------------------------------
        self.btn = tk.Button(
            inner,
            text="Knock & Connect",
            bg=ACCENT,
            fg="#ffffff",
            activebackground=ACCENT_HVR,
            activeforeground="#ffffff",
            font=_font(11, "bold"),
            relief="flat",
            cursor="hand2",
            command=self._on_knock,
        )
        self.btn.pack(fill="x", ipady=6, pady=(0, 12))

        # -- Status label (wrapping enabled) --------------------------------
        self.status = tk.Label(
            inner,
            text="Ready",
            bg=BG_CARD,
            fg=TEXT_SEC,
            font=_mono(9),
            anchor="w",
            justify="left",
            wraplength=380,
        )
        self.status.pack(fill="x")

    # ---- actions ----------------------------------------------------------
    def _set_status(self, text, colour=TEXT_SEC):
        if not self._closing:
            self.status.configure(text=text, fg=colour)

    def _on_knock(self):
        if self._busy.is_set():
            return

        host = self.var_host.get().strip()
        user = self.var_user.get().strip()

        # -- Input validation (regex) ----------------------------------------
        err = _validate_input(host, "hostname")
        if err:
            self._set_status(err, ERROR)
            return
        err = _validate_input(user, "SSH user")
        if err:
            self._set_status(err, ERROR)
            return

        self._busy.set()
        self.btn.configure(state="disabled", bg="#475569")
        self._set_status("Starting knock sequence...", ACCENT)

        t = threading.Thread(target=self._knock_thread, args=(host, user), daemon=True)
        t.start()

    def _knock_thread(self, host, user):
        try:
            for i, port in enumerate(KNOCK_SEQ, 1):
                self._safe_after(
                    0, self._set_status,
                    "Knocking port %d (%d/%d)..." % (port, i, len(KNOCK_SEQ)),
                    ACCENT,
                )
                knock(host, port)
                time.sleep(KNOCK_DELAY)

            self._safe_after(0, self._set_status, "Knock complete -- verifying SSH port...", SUCCESS)
            time.sleep(0.3)

            # -- DNS / port pre-validation ----------------------------------
            if not _probe_port(host, SSH_PORT, timeout=3.0):
                self._safe_after(
                    0, self._set_status,
                    "Warning: SSH port %d not reachable yet -- launching anyway..." % SSH_PORT,
                    WARN,
                )
                time.sleep(0.5)
            else:
                self._safe_after(0, self._set_status, "SSH port open -- launching terminal...", SUCCESS)
                time.sleep(0.2)

            err = launch_ssh(host, user, SSH_PORT)
            if err:
                self._safe_after(0, self._set_status, err, ERROR)
            else:
                self._safe_after(0, self._set_status, "SSH session launched.", SUCCESS)

        except socket.gaierror:
            self._safe_after(
                0, self._set_status,
                "DNS lookup failed for %s" % host, ERROR,
            )
        except Exception as exc:
            self._safe_after(0, self._set_status, str(exc), ERROR)
        finally:
            self._safe_after(0, self._finish)

    def _finish(self):
        self._busy.clear()
        self.btn.configure(state="normal", bg=ACCENT)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    root = tk.Tk()
    KnockApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()
